config/routes.rb
Rails.application.routes.draw do

  get '/' => 'central#index', as: :root

  resources :projects do
    resources :tasks
  end

  resources :users

  ## here be the guards
  get '/log-in' => "sessions#new"
  post '/log-in' => "sessions#create", as: :log_me_in
  get '/log-out' => "sessions#destroy", as: :log_me_out
end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :user
  has_many   :tasks, dependent: :destroy
  validates  :title, presence: true, uniqueness: true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :projects, dependent: :destroy
  has_many :tasks, through: :projects


  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  inherit_resources

  protect_from_forgery with: :exception
  before_filter        :require_login
  respond_to           :json
  actions              :all

  helper_method        :current_user

  def require_login
    unless current_user
      redirect_to log_in_path, :alert => "You must be logged in!"
    end
  end

  def current_user
    return @current_user if defined?(@current_user)

    if session[:user_id]
      user = User.where(:id => session[:user_id]).first
      if user
        @current_user = user
      else
        session[:user_id] = nil
      end
    end
  end
end

app/controllers/central_controller.rb
class CentralController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  private

  def project_params
    params.require(:project).permit(:title, :note, :user_id)
  end

  def begin_of_association_chain
    current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      flash[:success] = "Welcome back, #{user.email}"
      redirect_to root_path
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Come back soon!"
    redirect_to "/"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  belongs_to :project

  private

  def task_params
    params.require(:task).permit(:title, :note, :completed, :project_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'Right on! Start TAKING CARE OF BUSINESS!'
      redirect_to "/"
    else
      flash[:alert] = "Something went wrong. Let's try again."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yield?(key, default = "")
    content_for?(key) ? yield(key) : default
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/central/index.html.haml
%ng-include{ src: "'manage'",
  'ng-controller' => 'manageController as mCtrl' }

app/views/layouts/_messages.html.haml
.row
  .small-12.column
    .small-2.column
    .small-8.column
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{class: "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
            = content_tag :div, msg
            %a.close{href: "#"} ×
    .small-2.column

app/views/layouts/_navigation.html.haml
%nav.top-bar#nav{ data: { topbar: "" }, role: "navigation" }
  %ul.title-area
    %li.left_padding= link_to 'Home', root_path
    %li.toggle-topbar.menu-icon
      %a{href: "#"} Menu
  .top-bar-section
    %ul.right
      - if current_user
        %li= link_to 'Log Out', log_me_out_path
      - else
        %li= link_to 'Log In', log_in_path
        %li= link_to 'I\'m New', new_user_path

app/views/layouts/application.html.haml
!!!
%html{'ng-app' => 'todo.main' }
  %head
    %meta{ content: "width=device-width, initial-scale=1.0", name: "viewport" }/
    %title= yield?(:title, I18n.t("page.title"))
    %meta{ content: yield?(:description, I18n.t("meta.desc")),
    name: I18n.t("meta.name") }/
    = stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track" => true
    = stylesheet_link_tag "application",
      "http://fonts.googleapis.com/css?family=Roboto:400,700,300|Press+Start+2P)"
    = favicon_link_tag
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header= render "layouts/navigation"
    %main{ role: "main" }
      = render "layouts/messages"
      = yield

app/views/users/new.html.haml
.row
  .small-12.column
    %h3.name TAKING CARE OF (your) BUSINESS
    %h3 We care about your privacy. Hide your business from others.
    = form_for @user do |f|
      - if @user.errors.any?
        .error_messages
          %h2 Form is invalid
          %ul
            - for message in @user.errors.full_messages
              %li= message
      %p
        = f.label :email
        %br
        = f.text_field :email
      %p
        = f.label :password
        %br
        = f.password_field :password
      %p
        = f.label :password_confirmation
        %br
        = f.password_field :password_confirmation
      %p= f.submit 'Let\'s Do This!',:class => "round small button"